sudo: required
services:
  - docker
before_install:
  - docker build -t thomaslong/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true thomaslong/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: frontend
  env: Frontend-env
  bucket_name: elasticbeanstalk-us-east-1-863198229499
  bucket_path: docker
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
